version: "3.9"
services:
  webserver:
    build: ./server
    ports:
      - "3000:3000"
  db:
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ghchat
      MYSQL_USER: root
      MYSQL_PASSWORD: ghchat@123
      MYSQL_ROOT_PASSWORD: strongrootpassword
  # ALTER USER root IDENTIFIED WITH mysql_native_password BY 'ghchat@123';
