version: "3.9"
services:
  webserver:
    build: ./server
    ports:
      - "3000:3000"
  webapp:
    build: ./
    ports: 
      - "80:80"
  db:
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ghchat
      MYSQL_USER: root
      MYSQL_PASSWORD: ghchat@123
      MYSQL_ROOT_PASSWORD: strongrootpassword
    volumes: 
      - $PWD/data:/var/lib/mysql
  # ALTER USER root IDENTIFIED WITH mysql_native_password BY 'ghchat@123';
