version: "3.9"
services:
  webserver:
    build: ./server
  db:
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ghchat@123
      